@extends('layouts.public')
@section('title', 'Junta Administrativa y transparencia - CTP Roberto Gamboa Valverde')
@section('content')
<main class="service-page"><header class="service-hero"><div><span>Gobernanza institucional</span><h1>Junta Administrativa y transparencia</h1><p>{{ $page?->summary ?: 'Información institucional verificada sobre integración, proyectos, procesos e informes.' }}</p></div></header>
<div class="service-shell">
@if($page?->content)<section class="board-introduction">{!! $page->content !!}</section>@endif
<section><div class="section-heading"><div><span>Integración vigente</span><h2>Miembros de la Junta Administrativa</h2></div></div><div class="board-member-grid">@forelse($members as $member)<article class="board-member-card"><i class="fa-solid fa-user-tie"></i><div><h3>{{ $member->name }}</h3><p>{{ $member->position }}</p><small>@if($member->term_starts_at || $member->term_ends_at)Periodo: {{ $member->term_starts_at?->format('d/m/Y') ?: 'sin fecha inicial' }} — {{ $member->term_ends_at?->format('d/m/Y') ?: 'vigente' }}<br>@endif Verificado: {{ $member->verified_at->format('d/m/Y') }} · Fuente: {{ $member->source }}</small></div></article>@empty<div class="news-empty"><i class="fa-solid fa-people-group"></i><h2>Integración pendiente de verificación</h2><p>Los nombres y cargos se publicarán cuando exista respaldo institucional vigente.</p></div>@endforelse</div></section>
<section class="transparency-section"><div class="section-heading"><div><span>Rendición de cuentas</span><h2>Proyectos, procesos e informes</h2></div></div>
@php($labels=['project'=>'Proyectos','process'=>'Procesos','report'=>'Informes'])
<div class="transparency-columns">@foreach($labels as $type=>$label)<div class="transparency-column"><h3>{{ $label }}</h3>@forelse($records->get($type, collect()) as $record)<article class="transparency-card"><span>{{ $record->record_date?->format('d/m/Y') ?: $record->typeLabel() }}</span><h4>{{ $record->title }}</h4><p>{{ $record->summary }}</p>@if($record->content)<div class="transparency-content">{!! $record->content !!}</div>@endif<small>Responsable: {{ $record->responsible }} · Fuente: {{ $record->source }} · Verificado: {{ $record->verified_at->format('d/m/Y') }}</small>@if($record->documents->isNotEmpty())<div class="transparency-documents">@foreach($record->documents as $document)<a href="{{ asset('storage/'.ltrim($document->file_path, '/')) }}" target="_blank" rel="noopener"><i class="fa-regular fa-file-lines"></i> {{ $document->title }}</a>@endforeach</div>@endif</article>@empty<p class="muted">Sin publicaciones verificadas.</p>@endforelse</div>@endforeach</div></section>
</div></main>
@endsection
