@extends('layouts.admin')
@section('title', $service->exists ? 'Editar servicio' : 'Nuevo servicio')
@section('content')
<div class="page-heading"><h1><i class="fa-solid fa-hand-holding-heart"></i> {{ $service->exists ? 'Editar servicio' : 'Nuevo servicio' }}</h1><a class="button ghost" href="{{ route('admin.services.index') }}"><i class="fa-solid fa-arrow-left"></i> Volver</a></div>
<form class="card" method="POST" enctype="multipart/form-data" action="{{ $service->exists ? route('admin.services.update', $service) : route('admin.services.store') }}">@csrf @if($service->exists) @method('PUT') @endif
<div class="field-grid"><div class="field"><label for="name">Nombre</label><input id="name" name="name" value="{{ old('name', $service->name) }}" required></div><div class="field"><label for="slug">Dirección amigable</label><input id="slug" name="slug" value="{{ old('slug', $service->slug) }}" required></div></div>
<div class="field-grid"><div class="field"><label for="service_category_id">Categoría</label><select id="service_category_id" name="service_category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((int)old('service_category_id', $service->service_category_id) === $category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="field"><label for="audience">Público</label><select id="audience" name="audience">@foreach(['general'=>'General','students'=>'Estudiantes','families'=>'Familias','staff'=>'Personal','community'=>'Comunidad'] as $value=>$label)<option value="{{ $value }}" @selected(old('audience', $service->audience ?: 'general') === $value)>{{ $label }}</option>@endforeach</select></div></div>
<div class="field"><label for="summary">Resumen</label><textarea id="summary" name="summary" rows="3" required>{{ old('summary', $service->summary) }}</textarea></div>
<div class="field"><label for="description">Descripción HTML</label><textarea class="code-editor" id="description" name="description" rows="9">{{ old('description', $service->description) }}</textarea></div>
<div class="field"><label for="requirements">Requisitos HTML</label><textarea class="code-editor" id="requirements" name="requirements" rows="7">{{ old('requirements', $service->requirements) }}</textarea></div>
<div class="field-grid"><div class="field"><label for="responsible">Departamento responsable</label><input id="responsible" name="responsible" value="{{ old('responsible', $service->responsible) }}"></div><div class="field"><label for="schedule">Horario</label><input id="schedule" name="schedule" value="{{ old('schedule', $service->schedule) }}"></div></div>
<div class="field-grid"><div class="field"><label for="email">Correo</label><input id="email" name="email" type="email" value="{{ old('email', $service->email) }}"></div><div class="field"><label for="phone">Teléfono</label><input id="phone" name="phone" value="{{ old('phone', $service->phone) }}"></div></div>
<div class="field-grid"><div class="field"><label for="external_url">Enlace para realizar la gestión</label><input id="external_url" name="external_url" type="url" value="{{ old('external_url', $service->external_url) }}"></div><div class="field"><label for="attachment">Formulario o documento</label><input id="attachment" name="attachment" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx"></div></div>
<div class="field-grid"><div class="field"><label for="verified_at">Fecha de verificación</label><input id="verified_at" name="verified_at" type="date" value="{{ old('verified_at', $service->verified_at?->format('Y-m-d')) }}"></div><div class="field"><label for="sort_order">Orden</label><input id="sort_order" name="sort_order" type="number" min="0" value="{{ old('sort_order', $service->sort_order ?? 0) }}"></div></div>
<div class="field"><label for="status">Estado</label><select id="status" name="status"><option value="draft" @selected(old('status', $service->status ?: 'draft') === 'draft')>Borrador</option>@if(auth()->user()->hasPermission('services.publish'))<option value="published" @selected(old('status', $service->status) === 'published')>Publicado</option>@endif</select><small class="muted">Mantenga en borrador los datos que todavía no hayan sido confirmados.</small></div>
<button class="button secondary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Guardar servicio</button></form>
@endsection
