@extends('layouts.admin')
@section('title', 'Servicios')
@section('content')
<div class="page-heading"><div><h1><i class="fa-solid fa-hand-holding-heart"></i> Servicios</h1><p class="muted">Gestiones y apoyos disponibles para la comunidad educativa.</p></div><div class="actions"><a class="button ghost" href="{{ route('services.index') }}" target="_blank"><i class="fa-solid fa-eye"></i> Ver catálogo</a>@if(auth()->user()->hasPermission('services.manage'))<a class="button ghost" href="{{ route('admin.service-categories.index') }}"><i class="fa-solid fa-tags"></i> Categorías</a><a class="button" href="{{ route('admin.services.create') }}"><i class="fa-solid fa-plus"></i> Nuevo servicio</a>@endif</div></div>
<form class="filter-bar" method="GET"><label for="status">Estado</label><select id="status" name="status" onchange="this.form.submit()"><option value="">Todos</option><option value="draft" @selected(request('status') === 'draft')>Borrador</option><option value="published" @selected(request('status') === 'published')>Publicado</option></select></form>
<div class="card table-wrap"><table><thead><tr><th>Servicio</th><th>Categoría</th><th>Responsable</th><th>Verificación</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>
@forelse($services as $service)<tr><td><strong>{{ $service->name }}</strong><br><small class="muted">{{ $service->summary }}</small></td><td>{{ $service->category->name }}</td><td>{{ $service->responsible ?: 'Pendiente' }}</td><td>{{ $service->verified_at?->format('d/m/Y') ?: 'Sin verificar' }}</td><td><span class="badge {{ $service->status === 'published' ? 'success' : 'warning' }}">{{ $service->status === 'published' ? 'Publicado' : 'Borrador' }}</span></td><td><div class="actions">@if($service->status === 'published')<a class="button link" href="{{ route('services.show', $service) }}" target="_blank"><i class="fa-solid fa-eye"></i> Ver</a>@endif @if(auth()->user()->hasPermission('services.manage'))<a class="button link" href="{{ route('admin.services.edit', $service) }}"><i class="fa-solid fa-pen"></i> Editar</a><form method="POST" action="{{ route('admin.services.destroy', $service) }}" onsubmit="return confirm('¿Eliminar este servicio?')">@csrf @method('DELETE')<button class="button link" type="submit"><i class="fa-regular fa-trash-can"></i> Eliminar</button></form>@endif</div></td></tr>@empty<tr><td colspan="6">No hay servicios registrados. Agregue únicamente información confirmada.</td></tr>@endforelse
</tbody></table>{{ $services->links('pagination.admin') }}</div>
@endsection
