@extends('layouts.admin')
@section('title', $specialty->exists ? 'Editar especialidad' : 'Nueva especialidad')
@section('content')
<div class="page-heading"><h1><i class="fa-solid fa-screwdriver-wrench"></i> {{ $specialty->exists ? 'Editar especialidad' : 'Nueva especialidad' }}</h1><a class="button ghost" href="{{ route('admin.specialties.index') }}">Volver</a></div>
<form class="card" method="POST" enctype="multipart/form-data" action="{{ $specialty->exists ? route('admin.specialties.update', $specialty) : route('admin.specialties.store') }}">@csrf @if($specialty->exists) @method('PUT') @endif
<div class="field-grid"><div class="field"><label>Nombre oficial</label><input name="name" value="{{ old('name', $specialty->name) }}" required></div><div class="field"><label>Dirección amigable</label><input name="slug" value="{{ old('slug', $specialty->slug) }}" required></div></div>
<div class="field"><label>Resumen</label><textarea name="summary" rows="3">{{ old('summary', $specialty->summary) }}</textarea></div>
@foreach(['description'=>'Descripción','student_profile'=>'Perfil del estudiante','curriculum'=>'Áreas o plan de formación','career_opportunities'=>'Oportunidades profesionales verificadas'] as $field=>$label)<div class="field"><label>{{ $label }}</label><textarea class="code-editor" name="{{ $field }}" rows="8">{{ old($field, $specialty->{$field}) }}</textarea></div>@endforeach
<div class="field-grid"><div class="field"><label>Programa oficial DETCE/MEP</label><input name="official_program_url" type="url" value="{{ old('official_program_url', $specialty->official_program_url) }}"></div><div class="field"><label>Imagen</label><input name="image" type="file" accept="image/*"></div></div>
<div class="field-grid"><div class="field"><label>Coordinación responsable</label><input name="coordinator" value="{{ old('coordinator', $specialty->coordinator) }}"></div><div class="field"><label>Correo</label><input name="contact_email" type="email" value="{{ old('contact_email', $specialty->contact_email) }}"></div></div>
<div class="field-grid"><div class="field"><label>Fecha de verificación</label><input name="verified_at" type="date" value="{{ old('verified_at', $specialty->verified_at?->format('Y-m-d')) }}"></div><div class="field"><label>Orden</label><input name="sort_order" type="number" min="0" value="{{ old('sort_order', $specialty->sort_order ?? 0) }}"></div></div>
<div class="field"><label>Estado</label><select name="status"><option value="draft" @selected(old('status', $specialty->status ?: 'draft') === 'draft')>Borrador</option>@if(auth()->user()->hasPermission('specialties.publish'))<option value="published" @selected(old('status', $specialty->status) === 'published')>Publicada</option>@endif</select><small class="muted">Publique únicamente después de confirmar nombre, programa y contenido con Coordinación Técnica.</small></div>
<button class="button secondary"><i class="fa-solid fa-floppy-disk"></i> Guardar especialidad</button></form>
@endsection
