@extends('layouts.admin')
@section('title', $experience->exists ? 'Editar modalidad' : 'Nueva modalidad')
@section('content')
<div class="page-heading"><h1><i class="fa-solid fa-building-user"></i> {{ $experience->exists ? 'Editar modalidad' : 'Nueva modalidad' }}</h1><a class="button ghost" href="{{ route('admin.experiences.index') }}">Volver</a></div>
<form class="card" method="POST" action="{{ $experience->exists ? route('admin.experiences.update', $experience) : route('admin.experiences.store') }}">@csrf @if($experience->exists) @method('PUT') @endif
<div class="field-grid"><div class="field"><label>Título</label><input name="title" value="{{ old('title', $experience->title) }}" required></div><div class="field"><label>Dirección amigable</label><input name="slug" value="{{ old('slug', $experience->slug) }}" required></div></div>
<div class="field-grid"><div class="field"><label>Tipo</label><select name="type" required>@foreach(['professional_practice'=>'Práctica profesional','internship'=>'Pasantía','technical_visit'=>'Visita técnica'] as $value=>$label)<option value="{{ $value }}" @selected(old('type', $experience->type ?: 'professional_practice') === $value)>{{ $label }}</option>@endforeach</select></div><div class="field"><label>Duración</label><input name="duration" value="{{ old('duration', $experience->duration) }}" placeholder="Ej. Según lineamientos vigentes"></div></div>
<div class="field"><label>Resumen</label><textarea name="summary" rows="3">{{ old('summary', $experience->summary) }}</textarea></div>
@foreach(['description'=>'Descripción','requirements'=>'Requisitos','process_stages'=>'Etapas del proceso'] as $field=>$label)<div class="field"><label>{{ $label }}</label><textarea class="code-editor" name="{{ $field }}" rows="7">{{ old($field, $experience->{$field}) }}</textarea></div>@endforeach
<div class="field-grid"><div class="field"><label>Responsable institucional</label><input name="responsible" value="{{ old('responsible', $experience->responsible) }}" required></div><div class="field"><label>Horario o periodo</label><input name="schedule" value="{{ old('schedule', $experience->schedule) }}"></div></div>
<div class="field-grid"><div class="field"><label>Correo para estudiantes y familias</label><input type="email" name="contact_email" value="{{ old('contact_email', $experience->contact_email) }}"></div><div class="field"><label>Correo para empresas</label><input type="email" name="company_contact_email" value="{{ old('company_contact_email', $experience->company_contact_email) }}"></div></div>
<div class="field-grid"><div class="field"><label>Especialidades relacionadas</label><select name="specialty_ids[]" multiple size="7">@foreach($specialties as $specialty)<option value="{{ $specialty->id }}" @selected(in_array($specialty->id, old('specialty_ids', $experience->specialties->pluck('id')->all())))>{{ $specialty->name }}</option>@endforeach</select><small class="muted">Use Ctrl para seleccionar varias.</small></div><div class="field"><label>Documentos relacionados</label><select name="document_ids[]" multiple size="7">@foreach($documents as $document)<option value="{{ $document->id }}" @selected(in_array($document->id, old('document_ids', $experience->documents->pluck('id')->all())))>{{ $document->title }} · {{ $document->status === 'published' ? 'Publicado' : 'Borrador' }}</option>@endforeach</select></div></div>
<div class="field-grid"><div class="field"><label>Fecha de verificación</label><input name="verified_at" type="date" value="{{ old('verified_at', $experience->verified_at?->format('Y-m-d')) }}"></div><div class="field"><label>Orden</label><input name="sort_order" type="number" min="0" value="{{ old('sort_order', $experience->sort_order ?? 0) }}"></div></div>
<div class="field"><label>Estado</label><select name="status"><option value="draft" @selected(old('status', $experience->status ?: 'draft') === 'draft')>Borrador</option>@if(auth()->user()->hasPermission('experiences.publish'))<option value="published" @selected(old('status', $experience->status) === 'published')>Publicada</option>@endif</select><small class="muted">No publique nombres de empresas, convenios o cifras sin respaldo institucional.</small></div>
<button class="button secondary"><i class="fa-solid fa-floppy-disk"></i> Guardar modalidad</button></form>
@endsection
