@extends('layouts.admin')
@section('title',$document->exists?'Editar documento':'Nuevo documento')
@section('content')
<div class="page-heading"><h1>{{ $document->exists?'Editar documento':'Nuevo documento' }}</h1><a class="button ghost" href="{{ route('admin.documents.index') }}">Volver</a></div><form class="card" method="POST" enctype="multipart/form-data" action="{{ $document->exists?route('admin.documents.update',$document):route('admin.documents.store') }}">@csrf @if($document->exists)@method('PUT')@endif
<div class="field-grid"><div class="field"><label>Título</label><input name="title" value="{{ old('title',$document->title) }}" required></div><div class="field"><label>Dirección amigable</label><input name="slug" value="{{ old('slug',$document->slug) }}" required></div></div>
<div class="field-grid"><div class="field"><label>Categoría</label><select name="document_category_id">@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('document_category_id',$document->document_category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="field"><label>Archivo</label><input name="file" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx" @required(!$document->exists)></div></div>
<div class="field"><label>Descripción</label><textarea name="description" rows="3">{{ old('description',$document->description) }}</textarea></div>
<div class="field-grid"><div class="field"><label>Responsable</label><input name="responsible" value="{{ old('responsible',$document->responsible) }}" required></div><div class="field"><label>Versión</label><input name="version" value="{{ old('version',$document->version) }}"></div></div>
<div class="field-grid"><div class="field"><label>Emisión</label><input name="issued_at" type="date" value="{{ old('issued_at',$document->issued_at?->format('Y-m-d')) }}"></div><div class="field"><label>Expiración</label><input name="expires_at" type="date" value="{{ old('expires_at',$document->expires_at?->format('Y-m-d')) }}"></div></div>
<div class="field-grid"><div class="field"><label>Público</label><select name="audience">@foreach(['general'=>'General','students'=>'Estudiantes','families'=>'Familias','staff'=>'Personal','community'=>'Comunidad'] as $value=>$label)<option value="{{ $value }}" @selected(old('audience',$document->audience)===$value)>{{ $label }}</option>@endforeach</select></div><div class="field"><label>Reemplazado por</label><select name="replaced_by_id"><option value="">Vigente</option>@foreach($replacements as $replacement)<option value="{{ $replacement->id }}" @selected(old('replaced_by_id',$document->replaced_by_id)==$replacement->id)>{{ $replacement->title }}</option>@endforeach</select></div></div>
<div class="field-grid"><div class="field"><label>Verificación</label><input name="verified_at" type="date" value="{{ old('verified_at',$document->verified_at?->format('Y-m-d')) }}"></div><div class="field"><label>Orden</label><input name="sort_order" type="number" min="0" value="{{ old('sort_order',$document->sort_order??0) }}"></div></div>
<div class="field"><label>Estado</label><select name="status"><option value="draft">Borrador</option>@if(auth()->user()->hasPermission('documents.publish'))<option value="published" @selected(old('status',$document->status)==='published')>Publicado</option>@endif</select></div><button class="button secondary">Guardar documento</button></form>
@endsection
