@extends('layouts.admin')
@section('title', $event->exists ? 'Editar actividad' : 'Nueva actividad')
@section('content')
<div class="page-heading"><h1><i class="fa-solid fa-calendar-{{ $event->exists ? 'check' : 'plus' }}"></i> {{ $event->exists ? 'Editar actividad' : 'Nueva actividad' }}</h1><a class="button ghost" href="{{ route('admin.events.index') }}"><i class="fa-solid fa-arrow-left"></i> Volver</a></div>
<form class="card" method="POST" enctype="multipart/form-data" action="{{ $event->exists ? route('admin.events.update', $event) : route('admin.events.store') }}">@csrf @if($event->exists) @method('PUT') @endif
<div class="field-grid"><div class="field"><label for="title">Nombre</label><input id="title" name="title" value="{{ old('title', $event->title) }}" required></div><div class="field"><label for="slug">Dirección amigable</label><input id="slug" name="slug" value="{{ old('slug', $event->slug) }}" placeholder="feria-cientifica-2026" required></div></div>
<div class="field-grid"><div class="field"><label for="event_category_id">Categoría</label><select id="event_category_id" name="event_category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((int)old('event_category_id', $event->event_category_id) === $category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="field"><label for="audience">Público</label><select id="audience" name="audience"><option value="general" @selected(old('audience', $event->audience) === 'general')>General</option><option value="students" @selected(old('audience', $event->audience) === 'students')>Estudiantes</option><option value="families" @selected(old('audience', $event->audience) === 'families')>Familias</option><option value="staff" @selected(old('audience', $event->audience) === 'staff')>Personal</option><option value="community" @selected(old('audience', $event->audience) === 'community')>Comunidad</option></select></div></div>
<div class="field-grid"><div class="field"><label for="starts_at">Inicio</label><input id="starts_at" name="starts_at" type="datetime-local" value="{{ old('starts_at', $event->starts_at?->format('Y-m-d\TH:i')) }}" required></div><div class="field"><label for="ends_at">Finalización</label><input id="ends_at" name="ends_at" type="datetime-local" value="{{ old('ends_at', $event->ends_at?->format('Y-m-d\TH:i')) }}"></div></div>
<div class="field"><label class="toggle"><input type="checkbox" name="all_day" value="1" @checked(old('all_day', $event->all_day))><span>Actividad de todo el día</span></label></div>
<div class="field-grid"><div class="field"><label for="location">Lugar</label><input id="location" name="location" value="{{ old('location', $event->location) }}"></div><div class="field"><label for="registration_url">Enlace de inscripción o información</label><input id="registration_url" name="registration_url" type="url" value="{{ old('registration_url', $event->registration_url) }}" placeholder="https://..."></div></div>
<div class="field"><label for="summary">Resumen</label><textarea id="summary" name="summary" rows="3">{{ old('summary', $event->summary) }}</textarea></div>
<div class="field"><label for="description">Descripción HTML</label><textarea class="code-editor" id="description" name="description" rows="14">{{ old('description', $event->description) }}</textarea><small class="muted">Se eliminará contenido ejecutable peligroso al guardar.</small></div>
<div class="field-grid"><div class="field"><label for="image">Imagen destacada</label><input id="image" name="image" type="file" accept="image/*">@if($event->image_path)<small class="muted">Ya existe una imagen; seleccione otra para reemplazarla.</small>@endif</div><div class="field"><label for="attachment">Documento adjunto</label><input id="attachment" name="attachment" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx">@if($event->attachment_path)<small class="muted">Ya existe un documento; seleccione otro para reemplazarlo.</small>@endif</div></div>
<div class="field"><label for="status">Estado</label><select id="status" name="status"><option value="draft" @selected(old('status', $event->status ?: 'draft') === 'draft')>Borrador</option>@if(auth()->user()->hasPermission('events.publish'))<option value="published" @selected(old('status', $event->status) === 'published')>Publicado</option><option value="cancelled" @selected(old('status', $event->status) === 'cancelled')>Cancelado</option>@endif</select></div>
<button class="button secondary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Guardar actividad</button></form>
@endsection
