@extends('layouts.admin')
@section('title', 'Actividades')
@section('content')
<div class="page-heading"><div><h1><i class="fa-regular fa-calendar-days"></i> Actividades</h1><p class="muted">Eventos académicos, técnicos, culturales y administrativos.</p></div><div class="actions"><a class="button ghost" href="{{ route('calendar.index') }}" target="_blank"><i class="fa-solid fa-eye"></i> Ver calendario</a>@if(auth()->user()->hasPermission('events.manage'))<a class="button" href="{{ route('admin.events.create') }}"><i class="fa-solid fa-calendar-plus"></i> Nueva actividad</a>@endif</div></div>
<form class="filter-bar" method="GET"><label for="status">Estado</label><select id="status" name="status" onchange="this.form.submit()"><option value="">Todos</option><option value="draft" @selected(request('status') === 'draft')>Borrador</option><option value="published" @selected(request('status') === 'published')>Publicado</option><option value="cancelled" @selected(request('status') === 'cancelled')>Cancelado</option></select></form>
<div class="card table-wrap"><table><thead><tr><th>Actividad</th><th>Fecha</th><th>Categoría</th><th>Público</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>
@forelse($events as $event)<tr><td><strong>{{ $event->title }}</strong><br><small class="muted">{{ $event->location ?: 'Sin ubicación' }}</small></td><td>{{ $event->starts_at->translatedFormat('d M Y') }}<br><small class="muted">{{ $event->all_day ? 'Todo el día' : $event->starts_at->format('H:i') }}</small></td><td><span class="badge" style="border-left:4px solid {{ $event->category->color }}">{{ $event->category->name }}</span></td><td>{{ ['general'=>'General','students'=>'Estudiantes','families'=>'Familias','staff'=>'Personal','community'=>'Comunidad'][$event->audience] }}</td><td><span class="badge {{ $event->status === 'published' ? 'success' : ($event->status === 'cancelled' ? 'danger' : 'warning') }}">{{ ['draft'=>'Borrador','published'=>'Publicado','cancelled'=>'Cancelado'][$event->status] }}</span></td><td><div class="actions">@if($event->status !== 'draft')<a class="button link" href="{{ route('calendar.show', $event) }}" target="_blank"><i class="fa-solid fa-eye"></i> Ver</a>@endif @if(auth()->user()->hasPermission('events.manage'))<a class="button link" href="{{ route('admin.events.edit', $event) }}"><i class="fa-solid fa-pen"></i> Editar</a><form method="POST" action="{{ route('admin.events.destroy', $event) }}" onsubmit="return confirm('¿Eliminar definitivamente esta actividad?')">@csrf @method('DELETE')<button class="button link" type="submit"><i class="fa-regular fa-trash-can"></i> Eliminar</button></form>@endif</div></td></tr>@empty<tr><td colspan="6">Todavía no hay actividades registradas.</td></tr>@endforelse
</tbody></table>{{ $events->links('pagination.admin') }}</div>
@endsection
