@extends('layouts.admin')
@section('title', $article->exists ? 'Editar noticia' : 'Nueva noticia')
@section('content')
<div class="page-heading"><h1><i class="fa-regular fa-newspaper"></i> {{ $article->exists ? 'Editar noticia' : 'Nueva noticia' }}</h1><a class="button ghost" href="{{ route('admin.news.index') }}"><i class="fa-solid fa-arrow-left"></i> Volver</a></div>
<form class="card" method="POST" enctype="multipart/form-data" action="{{ $article->exists ? route('admin.news.update', $article) : route('admin.news.store') }}">@csrf @if($article->exists) @method('PUT') @endif
<div class="field-grid"><div class="field"><label for="title">Título</label><input id="title" name="title" value="{{ old('title', $article->title) }}" required></div><div class="field"><label for="slug">Dirección amigable</label><input id="slug" name="slug" value="{{ old('slug', $article->slug) }}" placeholder="comunicado-institucional" required></div></div>
<div class="field-grid"><div class="field"><label for="news_category_id">Categoría</label><select id="news_category_id" name="news_category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((int)old('news_category_id', $article->news_category_id) === $category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="field"><label for="status">Estado</label><select id="status" name="status"><option value="draft" @selected(old('status', $article->status ?: 'draft') === 'draft')>Borrador</option>@if(auth()->user()->hasPermission('news.publish'))<option value="published" @selected(old('status', $article->status) === 'published')>Publicado</option>@endif</select></div></div>
<div class="field"><label for="summary">Resumen</label><textarea id="summary" name="summary" rows="3" maxlength="1000" required>{{ old('summary', $article->summary) }}</textarea><small class="muted">Explique la información principal en uno o dos párrafos breves.</small></div>
<div class="field"><label for="content">Contenido HTML</label><textarea class="code-editor" id="content" name="content" rows="16" required>{{ old('content', $article->content) }}</textarea><small class="muted">El contenido ejecutable peligroso se eliminará al guardar.</small></div>
<div class="field-grid"><div class="field"><label for="published_at">Fecha de publicación</label><input id="published_at" name="published_at" type="datetime-local" value="{{ old('published_at', $article->published_at?->format('Y-m-d\TH:i')) }}"><small class="muted">Si publica y queda vacía, se utilizará la fecha actual.</small></div><div class="field"><label for="expires_at">Fecha de expiración</label><input id="expires_at" name="expires_at" type="datetime-local" value="{{ old('expires_at', $article->expires_at?->format('Y-m-d\TH:i')) }}"><small class="muted">Después de esta fecha dejará de mostrarse públicamente.</small></div></div>
<div class="field"><label class="toggle"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $article->is_featured))><span>Destacar esta noticia</span></label></div>
<div class="field-grid"><div class="field"><label for="image">Imagen destacada</label><input id="image" name="image" type="file" accept="image/*">@if($article->image_path)<small class="muted">Seleccione otra para reemplazar la imagen existente.</small>@endif</div><div class="field"><label for="attachment">Documento adjunto</label><input id="attachment" name="attachment" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx">@if($article->attachment_path)<small class="muted">Seleccione otro para reemplazar el documento existente.</small>@endif</div></div>
<button class="button secondary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Guardar noticia</button>
</form>
@endsection
