@extends('layouts.admin')
@section('title', $record->exists ? 'Editar publicación' : 'Nueva publicación')
@section('content')
<div class="page-heading"><h1><i class="fa-solid fa-scale-balanced"></i> {{ $record->exists ? 'Editar publicación' : 'Nueva publicación' }}</h1><a class="button ghost" href="{{ route('admin.board-records.index') }}">Volver</a></div>
<form class="card" method="POST" action="{{ $record->exists ? route('admin.board-records.update', $record) : route('admin.board-records.store') }}">@csrf @if($record->exists) @method('PUT') @endif
<div class="field-grid"><div class="field"><label>Título</label><input name="title" value="{{ old('title', $record->title) }}" required></div><div class="field"><label>Dirección amigable</label><input name="slug" value="{{ old('slug', $record->slug) }}" required></div></div>
<div class="field-grid"><div class="field"><label>Tipo</label><select name="type">@foreach(['project'=>'Proyecto','process'=>'Proceso','report'=>'Informe'] as $value=>$label)<option value="{{ $value }}" @selected(old('type', $record->type ?: 'project') === $value)>{{ $label }}</option>@endforeach</select></div><div class="field"><label>Fecha del registro</label><input type="date" name="record_date" value="{{ old('record_date', $record->record_date?->format('Y-m-d')) }}"></div></div>
<div class="field"><label>Resumen</label><textarea name="summary" rows="3">{{ old('summary', $record->summary) }}</textarea></div>
<div class="field"><label>Contenido</label><textarea class="code-editor" name="content" rows="9">{{ old('content', $record->content) }}</textarea></div>
<div class="field-grid"><div class="field"><label>Responsable</label><input name="responsible" value="{{ old('responsible', $record->responsible) }}" required></div><div class="field"><label>Fuente</label><input name="source" value="{{ old('source', $record->source) }}" required></div></div>
<div class="field"><label>Documentos relacionados</label><select name="document_ids[]" multiple size="7">@foreach($documents as $document)<option value="{{ $document->id }}" @selected(in_array($document->id, old('document_ids', $record->documents->pluck('id')->all())))>{{ $document->title }} · {{ $document->status === 'published' ? 'Publicado' : 'Borrador' }}</option>@endforeach</select><small class="muted">En la página pública solo aparecerán archivos vigentes y publicados.</small></div>
<div class="field-grid"><div class="field"><label>Fecha de verificación</label><input type="date" name="verified_at" value="{{ old('verified_at', $record->verified_at?->format('Y-m-d')) }}"></div><div class="field"><label>Orden</label><input type="number" min="0" name="sort_order" value="{{ old('sort_order', $record->sort_order ?? 0) }}"></div></div>
<div class="field"><label>Estado</label><select name="status"><option value="draft" @selected(old('status', $record->status ?: 'draft') === 'draft')>Borrador</option>@if(auth()->user()->hasPermission('board.publish'))<option value="published" @selected(old('status', $record->status) === 'published')>Publicada</option>@endif</select></div>
<button class="button secondary"><i class="fa-solid fa-floppy-disk"></i> Guardar publicación</button></form>
@endsection
